# Generated by Django 6.0.6 on 2026-06-24 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority'), ('admin', 'Admin')], default='citizen', max_length=20)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='Issues.userprofile'),
            preserve_default=False,
        ),
    ]
