# Generated by Django 6.0.6 on 2026-06-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0003_comment_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/images/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='issues/videos/'),
        ),
    ]
