# Generated by Django 6.0.6 on 2026-06-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0004_issue_image_issue_latitude_issue_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_updates', to='Issues.userprofile')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Issues.issue')),
            ],
        ),
    ]
