# Generated by Django 6.0.6 on 2026-06-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0005_authorityupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
