# Generated by Django 6.0.6 on 2026-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0006_issue_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='test123', max_length=100),
            preserve_default=False,
        ),
    ]
