# Generated by Django 6.0.6 on 2026-06-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
