# Generated by Django 6.0.6 on 2026-06-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0009_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
