# Generated by Django 6.0.6 on 2026-06-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0010_userprofile_login_otp_userprofile_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
