from django.urls import path
# from.views import create_issue
from .import views

urlpatterns = [
    path(
        "create/",
        views.create_issue,
        name="create_issue"
    ),
    path(
    "list/",
    views.issue_list,
    name="issue_list"
    ),
    path(
    "detail/<int:issue_id>/",
    views.issue_detail,
    name="issue_detail"
    ),
    path(
    "verify/<int:issue_id>/<str:vote_type>/",
    views.verify_issue,
    name="verify_issue"
    ),
    path(
    "authority-update/<int:issue_id>/",
    views.add_authority_update,
    name="add_authority_update"
    ),
    path(
    "dashboard/",
    views.dashboard,
    name="dashboard"
    ),
    path(
    "register/",
    views.register,
    name="register"
    ),
    path(
    "login/",
    views.login_view,
    name="login"
    ),
    path(
    "logout/",
    views.logout_view,
    name="logout"
    ),
    path(
    "leaderboard/",
    views.leaderboard,
    name="leaderboard"
    ),
    path(
    "profile/",
    views.profile,
    name="profile"
    ),
    path(
    "authority-dashboard/",
    views.authority_dashboard,
    name="authority_dashboard"
    ),
    path(
    "forgot-password/",
    views.forgot_password,
    name="forgot_password"
    ),
    path(
    "change-password/",
    views.change_password,
    name="change_password"
    ),
    path(
    "test-email/",
    views.test_email,
    name="test_email"
    ),
    path(
    "reset-password/<int:user_id>/",
    views.reset_password,
    name="reset_password"
    ),
    path(
    "notifications/",
    views.notifications,
    name="notifications"
    ),
    path(
    "verify-email/<str:token>/",
    views.verify_email,
    name="verify_email"
    ),
    path(
    "verify-login-otp/",
    views.verify_login_otp,
    name="verify_login_otp"
    ),
    path("", views.home, name="home"),
    path(
    "edit-profile/",
    views.edit_profile,
    name="edit_profile",
    ),
    path(
    "remove-profile-picture/",
    views.remove_profile_picture,
    name="remove_profile_picture"
    ),
    
]